config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'articles#index'
  resources :articles do
    collection do
      get 'school'
      get 'tech_blog'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  mount_uploader :url, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end

  def school
  end
  
  def tech_blog
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_blog_right.html.erb
<div class="right-var">
  <div class="right-var__profile">
    <h5 class="text-center font-weight-bolder py-3 text-white">プロフィール</h4>
    <%= image_tag "common/profile_image_1.jpg", class: "img-fluid mb-4"%> 
  </div>
  <div class="right-var__ad">
    <h5 class="text-center font-weight-bolder py-3 text-white">TECH::EXPERT受講検討の方にお得な情報</h4>
    <%= link_to "" do %>
      <%= image_tag "common/tech-expert_image_1.jpg", class: "img-fluid mb-4"%> 
    <% end %>
  </div>
</div>

app/views/articles/_contents.html.haml
.top__card__parts.col-xl-5.col-lg-7.p-0.mt-5.mx-auto.pb-3
  .top__card__parts__content
    = image_tag "common/image1.jpg", class: "img-fluid mb-4"
    .top__card__parts__content--text.text-left.col-11.m-auto
      %b スクール情報、比較
      %p 未経験者がエンジニアに転身するための、スクール情報を紹介。
      %p 自らの経験などを交えて、徹底的に調査比較を致しました。
      %p 直接メッセージを頂ければ相談にも乗りたいと思いますので、ぜひ参考にして下さい。
    = link_to school_articles_path, class: "text-center text-decoration-none" do
      %p.col-11.m-auto 詳細はこちら

app/views/articles/_footer.html.haml
.footer.mt-5
  .footer__text
    %p.m-0 © 2019 YJ. All right reserved.

app/views/articles/_nav-bar.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark
  %button.navbar-toggler{"aria-controls" => "navbar1", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbar1", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbar1.collapse.navbar-collapse.justify-content-end
    .navbar-nav.custom-navbar
      %p.navbar-brand Menu
      = link_to "/ Topページ", root_path, class: "nav-item nav-link"
      = link_to "/ スクール比較", school_articles_path, class: "nav-item nav-link"
      %a.nav-item.nav-link{:href => "#"} / 転職エージェント紹介
      = link_to "/ Tech系ブログ", tech_blog_articles_path, class: "nav-item nav-link"

app/views/articles/_paginate.html.haml
%ul.pagination.justify-content-between
  %li
    = link_to "＜ トップページ", root_path, class: "text-decoration-none"
  %li
    = link_to "転職エージェント紹介 ＞", root_path, class: "text-decoration-none"

app/views/articles/_school_text.html.erb
<div class="d-flex">
  <%= icon "far", "clock", class: "pt-1 pr-1" %>
  <p>2019-08-14</p>
</div>
<%= image_tag "common/image1.jpg", class: "img-fluid mb-4"%>
<p>数あるプログラミングスクールからいくつか厳選してご紹介します。<br>
  個人的な意見なので確定情報ではない場合があります。あらかじめご了承下さい。<br>
  あくまで未経験からスクール出てエンジニアになれた身として、<strong class="marker-yellow">自分の経験を交えた考えなどをまとめたものです。</strong><br>
  なので今後スクール決める上で、参考にして頂けると幸いです。
  <br><br>
  また、最終的に決めるのは自分です。<br>
  <strong class="marker-yellow__text-red">一通り無料カウンセリングや説明会を受けて自分に見合ったスクールを選ぶことをお勧めします！</strong><br>
  参加費は基本的に無料なので行って損はないです！(*ﾟ▽ﾟ*)
</p>

<h4 class="balloon"><b>おすすめプログラミングスクール紹介</b></h4>
<p>
  スクール紹介にいきたいと思います。<br>
  冒頭でも言いましたが、
  <strong class="marker-yellow">気になるところは全てカウンセリングや説明会に行くことをお勧めします。</strong>
  <strong class="marker-yellow__text-red">これをしないとお金や時間を無駄にします。</strong>
</p>

<!-- TECH::EXPERT -->
<%= render "schools/school_1" %>
<!-- デジタルハリウッド STUDIO by LIG -->
<%= render "schools/school_2" %>
<!-- Tech Boost -->
<%= render "schools/school_3" %>
<!-- DMM WEBCAMP -->
<%= render "schools/school_4" %>
<!-- ポテパンキャンプ -->
<%= render "schools/school_5" %>
<!-- ProgrammerCollege -->
<%= render "schools/school_6" %>
<!-- codecamp -->
<%= render "schools/school_7" %>

<h4 class="balloon"><b>まとめ</b></h4>
<p>
  以上、プログラミングスクールの紹介でした。<br>
  最後まとめついでにスクールを決める上でのアドバイスをしたいと思います。
  ただこれな個人的な意見なので、絶対に鵜呑みにはせず、<strong class="marker-yellow">最終的にはカウンセリングや体験などに行って自分の目で確かめてから決めてくだい</strong>。
</p>
<p>
  では本題ですが、個人的には<strong class="marker-yellow__text-red">教室を使った自習スタイルのスクールをお勧めします</strong>。
  理由は<strong class="marker-yellow">自走力が付く</strong>からです。さらに周りに同期などがいるので<strong class="marker-yellow">モチベーションも維持したまま</strong>学習に取り組む事ができます。
</p>
<p>
  確かにオンラインでも自走力が付くのですが、基本的には個人プレイになるので、途中でダレたり不安になったりして挫折・・・なんて可能性が高いです。
  そんな事になるならいっそう通ってしまった方が良いかなって思います。
</p>
<p>
  なので何度も言いますが、<strong class="marker-yellow__text-red">カウンセリングや体験などに積極的に参加して自分の目で確かめて「これなら出来そう！」と思ったら通ってみましょう</strong>。
</p>
<p>
  長くなりましたが以上となります。誰かの力になれたらと幸いです。
</p>

app/views/articles/index.html.haml
= render "shared/header"

.top.col-lg-9.col-md-8.mx-auto.my-5
  %h3.text-center.mb-0.pb-5 About This
  .top__text
    %b 「未経験エンジニア最短で一人前のエンジニアになるためには？」をテーマに考えたブログです。
    %p また 自分自身の成長のため、技術的な記事も書いています！
    %p こんなブログを立ち上げて偉そうなことかいてますが、自分もまだまだなので、一緒に成長していきたいと思いますし、そう言った考えに共感できる仲間に出会えたら良いなって思います。
    %p 駆け出しエンジニア、頑張ろーーー！！！
  // コンテンツ紹介
  %h4.text-center.mb-0.pt-4 コンテンツ紹介
  .top__card.d-xl-flex.justify-content-between
    = render "contents"
    = render "contents"
            
= render "footer"

app/views/articles/school.html.haml
= render "shared/header"

.blog.col-xl-10.d-xl-flex.mx-auto.mt-5
  .blog-left.col-xl-9.col-lg-10.m-lg-auto.p-0
    .blog-left--text.border.p-3
      = render "school_text"
    .paginate.pt-3
      = render "paginate"
    
  .blog-right.col-xl-3.ml-4.border.p-0
    = render "blog_right"

= render "footer"

app/views/articles/tech_blog.html.haml
= render "shared/header"
.tech-blog.d-lg-flex.justify-content-center.mt-5
  .tech-blog__left.border.col-lg-7.mr-3
    .tech-blog__left__title
      %h3.text-center.py-3 Tech Blog
    .card.col-10.m-auto
      .card__title
        %p タイトル：久しぶりにアプリ開いたらMysqlでエラーが出た。
      .card__discription
        %p 説明：しばらくお休みしていた個人アプリを開発環境で開いたら”Could not find mysql2-0.5.2 in any of the sources”と言われた。この時の対応を書きたいと思う。
      .card__in-a-word
        %p 一言で言うと：「bundle configのオプションは１つづつ加える」
      .card__url
        %p 参考URL：https://qiita.com/yj2222/items/1249736fa1ec6fb63a18
  .tech-blog__right.border.col-lg-3.ml-3
    %p 2019.08.23の記事
    %p 2019.08.23の記事
    %p 2019.08.23の記事
  

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MyTechBlog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/shared/_header.html.haml
.header
  .header__title
    = image_tag "common/tech_my_blog_logo.png", class: "pt-3 ml-3", style: "width: 300px;"
    -# %h1 ~ My Tech Blog ~
    = render "nav-bar"